travis:
  secure:
    BINSTAR_TOKEN: MllEuj0v+OHpTC5P4T7hhgQJLi/9cnZK0iwGyj0YuMV8vp8/O87dNn+iHJzYkg3Na/AhTOcgfQdo0QHkKUJ3pULT2uCp00ig2I8tE4NO0r4p9meXYxBoqnS8QquViBB1myPNYOYZKbl4SzAtaRbadTe4Inz8Qvg1X2nIbA4y5OXvhgtIhep8LTIl54Ke2Jv/mUi2VE59w/kX0ZA0EGrqPcLihA5wYHepRIQ8AWekr+dBsFkM0eqS3JxAa3pmLOSK78TQk3INJ52qcsUM846WcXc4bF8Ads7GyCXpu/5f5H71dP+YSXi5r8f31EGCyPSFZr6YJPzY7It8PRv6WRuRybHUxe98ocVY/DmMCmQLfP9I98JZ6lHHRl+CfTHKity1iFmiY0oOQnZG6oP/RiTbnF+iDaPuZQFJSrgNWT4rrMeZsOQURa4MJDyqz2Fu7LufGvM2q8X8siI6sinH7DuSA/i6FlLboCumF5J9mU8SeM0hAMdFBx1tcyiFD+14+gIyXJjwKSzQsSdln+C7MdyiYULZx6iV0aifckwCp1oZHaeJCWS6S+vQr7D11Hi5IB6Zj8Dpu8V/UtrQSHGq+RklVWk2Zv0Tn8ij2cKU7DAdWZ93pVdfuS3lWeLTOk+/oaiHIiRXb7fmkwomLiRxNWJAMmvlOaUfoPlPJjylMovZGx0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
