travis:
  secure:
    BINSTAR_TOKEN: CkbVZgVW5951kMxS5hAfwgTF0G4XEyof60AEZDAK3GIjPOkWg6E5VOSBqrRg9rZogspNyPJMq0OKuDghUg7ZWZ4SVcZXo/+t7N4iOOLiyRBjteawfp5rbMZMsqGDOCFpTnWJUX6UTUbyyAGdPcf+gUQ4paChYT61bdhxDHXh97HqbA920iibrOJImURtCJYEfdnrwsjJJJEdolUkgIN4ixXgnqn2qkjsat0UIZkKCifgzgO8BJTMZNWONMXPcapBMVZvEjEgBtQXbd1Q9LUmysWsAtwsbHWbEG8XrSh5PhQA+aUifbOhxuVyzbVDxlfXSACFGZoKN9aOuSMaydQppvAdKARTha+odCJUp4WU6GlNP5BsC8HAszpcCb3w8VF4+S3ukOWNqvRiJ/BWCK0lhs1a6eJiUxL2gYmUUmQ37mujZFnBOa/wHFUtDEvAibZwXA8SXQA5M2ptlRKW7XyECAJOyGaAWtG1NP2SaDnZah6cGXHI74SPPtSNzdvSuHi4nKv5pKvy9Ibvug3qFlrLwCHsWLs+XkpWn0xPiEuTKQIpw3B9UfSD9yMvmlH3KEurutXcoAYUtgIz66pyvP09g122hM7OpptEsOid0S9aVVdjLQiDkuhYjx8v20rmxSf+IaogSu+atnCNphhonN0tpH+7EOrzjFD92OuWVe3hRVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
